license = "BSD3"
with_readme = true

[files]
directories = ["src", "benches"]
templates = ["Cargo.toml","src/lib.rs", "src/main.rs", "benches/ {{ project }}.rs"]

[config]
version = "0.1.0"
version_control = "git"
