license = "BSD3"
with_readme = true

[files]
files = []
directories = ["src", "src/{{ Project }}", "src/Test"]
templates = ["{{ Project }}/Lib.idr","Main.idr","{{ project }}.ipkg",".gitignore", "Test/Spec.hs"]

[config]
version = "0.1.0"
version_control = "git"
