---

build: off

before_test:
  - choco install ghc
  - choco install cabal

test_script:
  - refreshenv
  - cabal new-update
  - cabal new-build all
  - ps: $directory = Get-ChildItem . -name -recurse {{ project }}.exe
  - ps: Copy-Item $directory {{ project }}-x86_64-pc-windows.exe
  - ps: Push-AppveyorArtifact {{ project }}-x86_64-pc-windows.exe

deploy:
  artifacts: {{ project }}-x86_64-pc-windows.exe
  provider: GitHub
  on:
    appveyor_repo_tag: true
  auth_token:
    secure: # put yours here

branches:
  only:
    - master
    - /\d+\.\d+\.\d+\.\d+.*$/
