name: build-wasm
run-name: ${{ github.actor }} is literally building wasm
on:
  push:
    branches:
      - master
jobs:
  build-the-wasm:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "latest"
          message: ${{ github.event.head_commit.message }}
      - name: setup the rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - name: setup rustup wiht wasm target
        run: rustup target add wasm32-wasi
      - name: compiling rust to wasm
        run: rustc gcd.rs --target wasm32-wasi
      - name: ensure the wasm is there and compiled
        run: ls -lths gcd.wasm

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v1.1.0
        with:
          version: ${{ github.ref }}
          path: ./CHANGELOG.md
          
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "gcd.wasm"
          body: ${{ steps.changelog_reader.outputs.log_entry }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"
